name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # node-version: [14.x]
        node-version: [14.x, 16.x]
        # os: [ubuntu-latest]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Install Nuxt
        run: pnpm run -r dev:prepare

      - name: Build
        run: pnpm run -r build

      - name: Test
        run: pnpm test

  lint-test:
    runs-on: ubuntu-latest
    name: 'Lint: node-16, ubuntu-latest'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Install Nuxt
        run: pnpm run -r dev:prepare

      - name: Build
        run: pnpm run -r build

      - name: Lint
        run: pnpm lint
