name: Deploy Doc

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Install Nuxt
        run: pnpm run -r dev:prepare

      - name: Build
        run: pnpm run -r build

      - name: Build Doc
        run: pnpm run -r docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/documentation/docs/.vitepress/dist
